excludeArtifacts:
  - scratch-test
  - src-env-specific-alias-pre
  - src-env-specific-pre
releasedefinitionProperties:
  promotePackagesBeforeDeploymentToOrg: uat
  skipIfAlreadyInstalled: true
  changelog:
    # repoUrl: https://github.com/TelenorNorgeInternal/s07491-sfw
    workItemFilters:
      - "CET-\\d{5}"
    workItemUrl: https://prima.corp.telenor.no/jira/browse/

