name: Clean pool
on:
  workflow_call:
    inputs:
      pool-tag:
        required: true
        type: string

env:
  SFPOWERSCRIPTS_SPLUNK: ${{ vars.SFPOWERSCRIPTS_SPLUNK }}
  SFPOWERSCRIPTS_SPLUNK_API_KEY: ${{ secrets.SFPOWERSCRIPTS_SPLUNK_API_KEY }}
  SFPOWERSCRIPTS_SPLUNK_HOST: ${{ vars.SFPOWERSCRIPTS_SPLUNK_HOST}}

jobs:
  clean-pool:
    name: "Clean ${{ inputs.pool-tag }} pool"
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp-rc:alpha

    steps:
      - uses: actions/checkout@v2

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: "Drop the pool"
        run: "sfp pool:delete -t ${{ inputs.pool-tag }} -v devhub"
