name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  SFPOWERSCRIPTS_SPLUNK: ${{ vars.SFPOWERSCRIPTS_SPLUNK }}
  SFPOWERSCRIPTS_SPLUNK_API_KEY: ${{ secrets.SFPOWERSCRIPTS_SPLUNK_API_KEY }}
  SFPOWERSCRIPTS_SPLUNK_HOST: ${{ vars.SFPOWERSCRIPTS_SPLUNK_HOST}}

jobs:
  deploy:
    name: "Deploy to ${{ vars.ORG_ALIAS }} environment"
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp-rc:alpha
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          name: quickbuild-artifacts
          path: artifacts

      - name: "npm install"
        run: |
          npm install

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: "Authenticate to ${{ vars.ORG_ALIAS }}"
        run: |
          echo "${{ secrets.ENV_SFDX_AUTH_URL }}" > ./env_authfile
          sfdx auth:sfdxurl:store -f ./env_authfile -a ${{ vars.ORG_ALIAS }}

      - name: "Deploy to ${{ vars.ORG_ALIAS }}"
        run: |
          sfp dependency:install -u ${{ vars.ORG_ALIAS }} -v devhub
          sfp orchestrator:deploy -u ${{ vars.ORG_ALIAS }}  --skipifalreadyinstalled -g "::group::,::endgroup::"
