name: Create Review Org

on:
  issue_comment:
    types: [created]

jobs:
  create-review-org:
    if: contains(github.event.comment.body, '/review-org') && github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp-rc:alpha
    permissions:
      contents: read
      pull-requests: write
      issues: write
    env:
      pool-tag: ci
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/merge"
          fetch-depth: 0

      - name: "npm install"
        run: |
          npm install

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf auth sfdxurl store -f authfile -a devhub

      - name: "Push source to scratch org"
        run: "sfp orchestrator:validate -p ${{ env.pool-tag }} -v devhub"

      - name: "Store scratch org auth url"
        id: org-info
        run: |
          sf org display --verbose --json | jq '.result.sfdxAuthUrl' > ./auth_url
          echo "auth_url=$(cat ./auth_url)" >> $GITHUB_ENV

      - name: "Store scratch org login url"
        id: login-url
        run: |
          sf org open -r --json | jq '.result.url' > ./login_url
          echo "login_url=$(cat ./login_url)" >> $GITHUB_ENV

      - name: Post Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const auth_url = process.env.auth_url;
            const login_url = process.env.login_url;
            const output = `Review org 🌩️
              auth_url: ${auth_url}
              login_url: ${login_url}
            `.replace(/"/g, '');
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: output,
            };
            github.issues.createComment(comment);
