name: "PR Validation"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  validate:
    name: "Validate metadata"
    uses: b64hub/sf-actions/.github/workflows/simple-validate.yml@main
    with:
      source-dir: src/apex/utils
    secrets: inherit
