name: "PR Validation"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
    paths:
      - "src/**"
      - src**
  workflow_dispatch:

jobs:
  validate:
    name: "Validate metadata"
    uses: b64hub/sf-actions/.github/workflows/validate.yml@main
    with:
      pool-tag: ci
    secrets: inherit
