name: "Replenish CI Pools - Auto Triggered"

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Commit Id from where the pools should be created"
        required: false
        default: "main"
  # schedule:
  #   - cron: "0 02 * * *"

jobs:
  prepare-ci-pool:
    uses: b64hub/sf-actions/.github/workflows/prepare-pool.yml@main
    with:
      pool-tag: ci
      git-ref: ${{ inputs.git-ref }}
    secrets: inherit

  prepare-dev-pool:
    needs: prepare-ci-pool
    uses: b64hub/sf-actions/.github/workflows/prepare-pool.yml@main
    with:
      pool-tag: dev
      git-ref: ${{ inputs.git-ref }}
    secrets: inherit
