name: "CI Pipeline - Auto Triggered"

on:
  push:
    branches:
      - main
    paths:
      - "src**"
      - "src/**"
      - "!src/**/*.md"
      - "!src**/*.md"

  workflow_dispatch:

jobs:
  quickbuild:
    uses: b64hub/dx-actions/.github/workflows/quickbuild.yml@main
    secrets: inherit

  build-publish:
    uses: b64hub/dx-actions/.github/workflows/build-publish.yml@main
    needs: quickbuild
    permissions:
      packages: write
      contents: write
    secrets: inherit