name: "Deployment pipeline"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev
        required: true

jobs:
  deploy-env:
    uses: b64hub/dx-actions/.github/workflows/deploy.yml@main
    needs: quickbuild
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

