name: "Release"

on:
  workflow_dispatch:
    inputs:
      release-def-path:
        description: "Path to release definition file"
        required: true

jobs:
  release:
    uses: b64hub/sf-actions/.github/workflows/release.yml@main
    strategy:
      matrix:
        org: [prod]
    if: startsWith(github.ref, 'refs/tags/release/')
    with:
      release-def-path: ${{ inputs.release-def-path }}
      org: ${{ matrix.org }}
    permissions:
      packages: write
      contents: write
    secrets: inherit
