name: Release to environment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      release-def-path:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      release-def-path:
        required: true
        type: string

# env:
#   SFPOWERSCRIPTS_SPLUNK: "${{ vars.SPLUNK }}"
#   SFPOWERSCRIPTS_SPLUNK_API_KEY: "${{ secrets.SPLUNK_API_KEY }}"
#   SFPOWERSCRIPTS_SPLUNK_HOST: ${{ vars.SPLUNK_HOST}}

jobs:
  release:
    name: "Release to ${{ vars.ORG_ALIAS }} environment"
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp-rc:alpha
    permissions:
      contents: write
      packages: write
      pull-requests: write
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "npm install"
        run: |
          npm install

      - name: Authenticate to ${{ vars.ORG_ALIAS  }} environment
        run: |
          echo "${{ secrets.ENV_SFDX_AUTH_URL }}" > ./authfile
          sf auth sfdxurl store -f ./authfile -a ${{ vars.ORG_ALIAS }}

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf auth sfdxurl store  -f authfile -a devhub

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      # Release to environment
      - name: "Release to ${{ vars.ORG_ALIAS }}"
        run: 'sfp orchestrator:release -u ${{ vars.ORG_ALIAS }} -v devhub -p ${{ inputs.release-def-path }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::"'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
