name: "CI Pipeline - Release Build - Auto Triggered"

on:
  push:
    branches:
      - release/**
    paths:
      - src/**
      - src**
  workflow_dispatch:

jobs:
  build-publish:
    uses: ./.github/workflows/build-publish.yml
    permissions:
      packages: write
      contents: write
    secrets: inherit
