name: "CI Pipeline - Release Build - Auto Triggered"

on:
  push:
    branches:
      - release/**
    paths:
      - src/**
      - src**
  workflow_dispatch:

jobs:
  build-publish:
    uses: b64hub/sf-actions/.github/workflows/build-publish.yml@main
    permissions:
      packages: write
      contents: write
    secrets: inherit
